# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rfq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rfq.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\trfq.proto\"w\n\rClientRequest\x12\x0e\n\x06rfq_id\x18\x01 \x01(\x05\x12\x12\n\naccount_id\x18\x02 \x01(\x05\x12\x16\n\x0eproduct_number\x18\x03 \x02(\x05\x12\x18\n\x10product_category\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05')
)




_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfq_id', full_name='ClientRequest.rfq_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='ClientRequest.account_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_number', full_name='ClientRequest.product_number', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_category', full_name='ClientRequest.product_category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='ClientRequest.quantity', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUEST,
  __module__ = 'rfq_pb2'
  # @@protoc_insertion_point(class_scope:ClientRequest)
  ))
_sym_db.RegisterMessage(ClientRequest)


# @@protoc_insertion_point(module_scope)
